config/routes.rb
Rails.application.routes.draw do
  root 'overview#index', via: :get

  resources 'recipes', only: [:show, :new, :create, :edit, :update]
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy

  accepts_nested_attributes_for :ingredients, :steps

  enum status: [:draft, :published]
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(new_recipe_params)
    @recipe.save

    redirect_to edit_recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.ingredients.build if @recipe.ingredients.count < 1
    @recipe.steps.build if @recipe.steps.count < 1
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.update(update_recipe_params)

    redirect_to @recipe
  end

  private

  def new_recipe_params
    params.require(:recipe).permit(:title)
  end

  def update_recipe_params
    params.require(:recipe).permit(
      :title,
      ingredients_attributes: [:id, :ingredient, :measurement],
      steps_attributes: [:id, :content]
    ) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gomen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/overview/index.html.haml
= link_to 'Add Recipe', new_recipe_path
%hr
- @recipes.each do |recipe|
  = link_to recipe.title, edit_recipe_path(recipe)
  %br

app/views/recipes/edit.html.haml
%h1
  =@recipe.title
  %small= @recipe.status

= simple_form_for @recipe do |f|
  = f.input :title
  %h2 Ingredients
  = f.simple_fields_for :ingredients do |i_form|
    = i_form.input :ingredient
    = i_form.input :measurement 
  %h2 Steps
  = f.simple_fields_for :steps do |s_form|
    = s_form.input :content, label: '1'
  = f.submit 'Save Recipe'

app/views/recipes/new.html.haml
%h1 New Recipe

= simple_form_for @recipe do |f|
  = f.input :title
  = f.submit 'Proceed'

app/views/recipes/show.html.haml
%h1= @recipe.title
%h2 Ingredients
%ol
  - @recipe.ingredients.each do |ingredient|
    %li= "#{ingredient.measurement} #{ingredient.ingredient}"
%h2 Steps
%ol
  - @recipe.steps.each do |step|
    %li= step.content